version: '3'
services:
  odoo:
    image: odoo:15.0
    container_name: odoo_issa
    depends_on:
      - db
    ports:
      - "8070:8069"
    environment:
      - HOST=db
      - USER=odoo
      - PASSWORD=odoo
    volumes:
      - odoo-addons:/mnt/extra-addons
      - odoo-data:/var/lib/odoo
    restart: unless-stopped

  db:
    image: postgres:12
    container_name: postgres_prod
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=odoo
      - POSTGRES_PASSWORD=odoo
    volumes:
      - odoo-db-data:/var/lib/postgresql/data
    restart: unless-stopped


  caddy:
    image: caddy:latest
    # build:
    #   context: ./ # Chemin vers le répertoire contenant le Dockerfile
    container_name: caddy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - caddy-data:/data
      - caddy-config:/config
      - ./Caddyfile:/etc/caddy/Caddyfile
    restart: unless-stopped

volumes:
  odoo-addons:
  odoo-data:
  odoo-db-data:
  caddy-data:
  caddy-config:


